language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "lts/*"

install:
  - npm install
script:
  - npm run test:ci
  - npm run integration-test:ci

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "10"
      script: echo "Deploying to npm"
      before_deploy:
        - npm run clean
        - npm run compile:prod
        - cp -r dist/src/* .
      deploy:
        provider: npm
        edge: true
        email: "$NPM_EMAIL"
        api_key: "$NPM_AUTH_TOKEN"
        skip_cleanup: true
        on:
          tags: true
